language: go

branches:
    only:
        - master

go:
    - '1.16.x'
    - '1.17.x'

before_install:
    - go get -t -v ./...

script:
    - go test
    - go test -bench . -benchmem
    - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
    - bash <(curl -s https://codecov.io/bash)
